### ISSUE TITLE
Contract labeling

### ISSUE THREAD

**Issue by FloppyDisck** [phi-labs-ltd/msig-launcher#4]
To prevent labeling issues, they label should be build out of a given String, the signing user's address and the block height.

```rust
// The full label as seed on the blockchain
pub type FullLabel: String;
// The partial label without blockheight and address
pub type Label: String;
// Used to find all contracts with that label
pub static LABEL_MSIGS: Map<(Address, Label, BlockHeight), FullLabel> = ...;
// Used to find all contracts by that address
pub static USER_MSIGS: Map<(Label, Address, BlockHeight), FullLabel> = ...;

pub static MSIGS: Map<FullLabel, MSig> = ...;
```

**Comment by pyncz** [comment]
I don't like using label as the key, especially with block height in it. Why not just keep core msig contract's address as the key for its details?

Imagine user connects to the UI. We need to query their msig(s) to show what's available. We don't know the height, we don't know the label, we know only the address.

**Comment by pyncz** [comment]
Why not just 
```rust
/// Map to link a user address to the list of their multisigs' details
pub static MULTISIGS: Map<&Addr, Vec<MSig>> = Map::new("multisigs");
```
or
```rust
/// Map of multisig details by main Msig address
pub static MULTISIGS: Map<&Addr, MSig> = Map::new("multisigs");
/// Map of the msig addresses by user address
pub static USERS: Map<&Addr, Vec<Addr>> = Map::new("users");
```

**Comment by FloppyDisck** [comment]
> I don't like using label as the key, especially with block height in it. Why not just keep core msig contract's address as the key for its details?
> 
> Imagine user connects to the UI. We need to query their msig(s) to show what's available. We don't know the height, we don't know the label, we know only the address.

Thats the whole point of using Map, as long as you have the first value inside the key you can query the rest. Meaning you can get all multisigs with just `Addr` on `LABEL_MSIGS`
